export const ApiRoute = {
  register: "/user/create-user",
  login: "/user/login",
  getform: "/form",
  createreport: "/report/create-report",
  updatereport: "/report/update-report",
  getreport: "/report",
  deleteReport: "/report/delete",
  getanimals: "/animal",
  getUser: "/user/get-user",
  getSchedule: "/schedule/get-user-schedule",
  deleteUser: "/user/delete-user",
  createUser: "/user/create-user",
  updateUser: "/user/update-user",
};
